# imports
import os

# variables
DATA_DOWNLOAD_URLS = [
    'https://drive.google.com/uc?export=download&id=0BzJvaZGFryOnQkh2UHhpLWJyYnM',
    'https://drive.google.com/uc?export=download&id=0BzJvaZGFryOnTmYwVFRhOGR5Qnc'
]

TRAINING_PATH = 'model'
DATA_PATH = 'data'

DEFAULT_INPUTS_FILE_PATH = os.path.join(DATA_PATH, 'inputs.txt')
DEFAULT_OUTPUTS_FILE_PATH = os.path.join(DATA_PATH, 'outputs.txt')

DEFAULT_INPUT_VOCAB_SIZE = 20000
DEFAULT_OUTPUT_VOCAB_SIZE = 20000

DEFAULT_BUCKETS_STRING = '[(14, 14)]'
DEFAULT_DATA_SET_PATH = os.path.join(TRAINING_PATH, 'data_set.pkl')
PARAM_FILE_PATH = os.path.join(TRAINING_PATH, 'model_params.pkl')

DEFAULT_CHECKPOINT_INTERVAL = 500
DEFAULT_EVAL_INTERVAL = 500
DEFAULT_LOSS_CHECK_INTERVAL = 50
DEFAULT_CHECKPOINT_PATH = os.path.join(TRAINING_PATH, 'checkpoints')

DEFAULT_N_STEPS = 10000
DEFAULT_LAYER_SIZE = 256
DEFAULT_N_LAYERS = 3
DEFAULT_MAX_GRADIENT_NORM = 5.0
DEFAULT_BATCH_SIZE = 4
DEFAULT_LEARNING_RATE = 0.2
DEFAULT_LEARNING_RATE_DECAY_FACTOR = 0.9
DEFAULT_RNN_CELL = 'GRU'
DEFAULT_N_SAMPLES = 512
DEFAULT_FORWARD_ONLY = False
DEFAULT_N_EVAL_BATCHES = 25
